name: Build and test of Java Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setkup-java@v1
        with:
         jave-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
